// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD74QOygCB5F74UNluJpafsNW8HtQtw_Ss',
    appId: '1:907790733415:web:6c580e37c2af02534c04c2',
    messagingSenderId: '907790733415',
    projectId: 'vitashop-76ad5',
    authDomain: 'vitashop-76ad5.firebaseapp.com',
    storageBucket: 'vitashop-76ad5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6VGaOfwuveuLAiifimPy7zBD9EYpxuOw',
    appId: '1:907790733415:android:fa1eec60cab501c64c04c2',
    messagingSenderId: '907790733415',
    projectId: 'vitashop-76ad5',
    storageBucket: 'vitashop-76ad5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC86WH2PAc0vwWwl0FIidchoe4o3VM7kAw',
    appId: '1:907790733415:ios:f0a42712656ababe4c04c2',
    messagingSenderId: '907790733415',
    projectId: 'vitashop-76ad5',
    storageBucket: 'vitashop-76ad5.appspot.com',
    androidClientId: '907790733415-b975n2shg1bic768jfp6qo872s55o8cg.apps.googleusercontent.com',
    iosClientId: '907790733415-adaftd9diq2jfq0271gk7a8rsh7tq03l.apps.googleusercontent.com',
    iosBundleId: 'com.example.vitaShopUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC86WH2PAc0vwWwl0FIidchoe4o3VM7kAw',
    appId: '1:907790733415:ios:f0a42712656ababe4c04c2',
    messagingSenderId: '907790733415',
    projectId: 'vitashop-76ad5',
    storageBucket: 'vitashop-76ad5.appspot.com',
    androidClientId: '907790733415-b975n2shg1bic768jfp6qo872s55o8cg.apps.googleusercontent.com',
    iosClientId: '907790733415-adaftd9diq2jfq0271gk7a8rsh7tq03l.apps.googleusercontent.com',
    iosBundleId: 'com.example.vitaShopUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD74QOygCB5F74UNluJpafsNW8HtQtw_Ss',
    appId: '1:907790733415:web:aaa3a6e6640b14ee4c04c2',
    messagingSenderId: '907790733415',
    projectId: 'vitashop-76ad5',
    authDomain: 'vitashop-76ad5.firebaseapp.com',
    storageBucket: 'vitashop-76ad5.appspot.com',
  );

}